package eu.nk2.intercom.perf

const val TEST_BENCHMARK_WARMUP_COUNT = 100
const val TEST_BENCHMARK_REPEAT_BATCH_COUNT = 400
const val TEST_BENCHMARK_REPEAT_BATCH_WAIT_MS = 1000
const val TEST_BENCHMARK_REPEAT_COUNT = 100000

const val TEST_INTERFACE_INTERCOM_ID = "TEST_INTERFACE_INTERCOM_ID"