package eu.nk2.intercom.application

const val TEST_INTERFACE_INTERCOM_ID = "TEST_INTERFACE_INTERCOM_ID"
const val TEST_SECOND_INTERFACE_INTERCOM_ID = "TEST_SECOND_INTERFACE_INTERCOM_ID"

const val TEST_DELAYED_BENCHMARK_THREAD_COUNT = 20
const val TEST_DELAYED_BENCHMARK_REPEAT_COUNT = 10
const val TEST_DELAYED_BENCHMARK_DELAY_MS = 1
const val TEST_DELAYED_BENCHMARK_SECOND_DELAY_MS = 2
const val TEST_DELAYED_INTERFACE_INTERCOM_ID = "TEST_DELAYED_INTERFACE_INTERCOM_ID"
const val TEST_SECOND_DELAYED_INTERFACE_INTERCOM_ID = "TEST_SECOND_DELAYED_INTERFACE_INTERCOM_ID"

const val TEST_EXCEPTIONAL_INTERFACE_ID = "TEST_EXCEPTIONAL_INTERFACE_ID"